version: '3'
services:
    frontend: 
        restart: always
        image: 'dinhlongviolin1/frontend-app:latest'
        ports:
            - '8000:8000'
    backend:
        restart: always
        image: 'dinhlongviolin1/binance-data-backend:latest'
        ports:
            - '3000:3000'
    nginx:
        restart: always
        build: 
            dockerfile: Dockerfile
            context: ./nginx
        ports:
            - '80:80'
    newsscrape:
        restart: always
        image: 'dinhlongviolin1/news-scrape:latest'
    prediction:
        restart: 'always'
        image: 'dinhlongviolin1/prediction-prophet:latest'